# <center>**第7章**</center>
- <center>合并数据集</center>
- <center>重塑和轴转向</center>
- <center>离散化和面元划分</center>
- <center>检测和过滤异常值</center>
- <center>检测和过滤异常值</center>
- <center>计算指标/哑变量</center>
- <center>字符串操作</center>

**合并数据集**
- 数据·库风格的dataframe合并：merge  join
- 索引上的合并
- 轴向连接
- 合并重叠数据

In [2]:
from numpy.random import randn
import numpy as np
from pandas import Series, DataFrame
import pandas as pd

In [3]:
df1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                 'data1': range(7)})
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [10]:
df2 = DataFrame({'key': ['a', 'b', 'd'],
                 'data2': range(3)})
df2

key  data2
0   a      0
1   b      1
2   d      2

In [11]:
pd.merge(df2,df1)

key  data2  data1
0   a      0      2
1   a      0      4
2   a      0      5
3   b      1      0
4   b      1      1
5   b      1      6

In [12]:
pd.merge(df1,df2,on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [13]:
#列名不同也可以分别指定

In [14]:
df3 = DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                 'data1': range(7)})
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [15]:
df4 = DataFrame({'rkey': ['a', 'b', 'd'],
                 'data2': range(3)})
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [17]:
pd.merge(df3,df4,left_on='lkey',right_on = 'rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [19]:
pd.merge(df1,df2,how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [20]:
df1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                 'data1': range(6)})
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [21]:
df2 = DataFrame({'key': ['a', 'b', 'a', 'b', 'd'],
                 'data2': range(5)})
df2

key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [22]:
pd.merge(df1,df2,on='key',how='left')

key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0

In [23]:
pd.merge(df1,df2,how='inner')

key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   b      5      1
5   b      5      3
6   a      2      0
7   a      2      2
8   a      4      0
9   a      4      2

In [24]:
#多个键进行合并

In [25]:
left = DataFrame({'key1': ['foo', 'foo', 'bar'],
                  'key2': ['one', 'two', 'one'],
                  'lval': [1, 2, 3]})
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [26]:
right = DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                   'key2': ['one', 'one', 'one', 'two'],
                   'rval': [4, 5, 6, 7]})
right

key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [28]:
pd.merge(left,right,on = ['key1','key2'],how ='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

- merge函数的参数
  - on 
  - left_on
  - right_on
  - left_index
  - right_index
  - sort
  - suffixes
  - copy

**索引上的合并**

In [29]:
#列索引
left1 = DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],
                  'value': range(6)})
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [30]:
right1 = DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])
right1

group_val
a        3.5
b        7.0

In [31]:
pd.merge(left1,right1,left_on = 'key',right_index=True)


key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [32]:
#层次化索引

In [33]:
lefth = DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
                   'key2': [2000, 2001, 2002, 2001, 2002],
                   'data': np.arange(5.)})
lefth

key1  key2  data
0    Ohio  2000   0.0
1    Ohio  2001   1.0
2    Ohio  2002   2.0
3  Nevada  2001   3.0
4  Nevada  2002   4.0

In [34]:
righth = DataFrame(np.arange(12).reshape((6, 2)),
                   index=[['Nevada', 'Nevada', 'Ohio', 'Ohio', 'Ohio', 'Ohio'],
                          [2001, 2000, 2000, 2000, 2001, 2002]],
                   columns=['event1', 'event2'])
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [37]:
pd.merge(lefth,righth,left_on = ['key1','key2'],right_index=True)

key1  key2  data  event1  event2
0    Ohio  2000   0.0       4       5
0    Ohio  2000   0.0       6       7
1    Ohio  2001   1.0       8       9
2    Ohio  2002   2.0      10      11
3  Nevada  2001   3.0       0       1

**dataframe还有一个jion方法**

In [38]:
#轴向连接

In [39]:
arr = np.arange(12).reshape((3,4))

In [40]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
np.concatenate([arr,arr],axis = 1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [45]:
s1 = Series([0,1],index=['a','b'])

In [46]:
s2 = Series([2,3,4],index = ['a','b','c'])

In [47]:
s3 = Series([5,6],index = ['f','g'])

In [51]:
pd.concat([s1,s2,s3],axis =1)

d:\Users\Amazing\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1    2
a  0.0  2.0  NaN
b  1.0  3.0  NaN
c  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

#合并重叠数据
**可能有索引全部或部分重叠的两个数据集**

In [53]:
a = Series([np.nan,2.5,np.nan,3.5,4.5,np.nan])

**用于表达一种矢量化的 if-else**
ex:np.where(pd.isnull(a),b,a)

In [56]:
b = Series(np.arange(len(a),dtype=np.float64),index=['f','e','d','c','b','a'])

In [57]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64

In [58]:
b[-1] = np.nan

In [59]:
a

0    NaN
1    2.5
2    NaN
3    3.5
4    4.5
5    NaN
dtype: float64

In [63]:
np.where(pd.isnull(a),b,a)

array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [61]:
#Serise有一个combin_fist方法，实现的是也是一样的功能，而且还会进行数据对齐

In [62]:
b[:-2].combine_first(a[:2])

d:\Users\Amazing\Anaconda3\lib\site-packages\pandas\core\series.py:2275: RuntimeWarning: '<' not supported between instances of 'str' and 'int', sort order is undefined for incomparable objects
  new_index = self.index.union(other.index)


f    0.0
e    1.0
d    2.0
c    3.0
0    NaN
1    2.5
dtype: float64

In [64]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

**concat函数的用法**